-- MIGRACIÓN: Nombres de ejercicios en español.
-- Traduce solo `name` (lo visible). NO toca muscle/type/equipment porque
-- son códigos que usa la app (gráficos por zona muscular, filtros).
-- Idempotente: cada UPDATE matchea por nombre inglés exacto; si ya se
-- corrió, no encuentra filas y no hace nada. Ejecutar en SQL Editor.
-- Las filas duplicadas con igual nombre (ej: Neck-SMR x2) se traducen juntas.

UPDATE public.exercises SET name = 'Auto-masaje de aductores' WHERE name = 'Adductor SMR';
UPDATE public.exercises SET name = 'Aductores / Ingle' WHERE name = 'Adductor/Groin';
UPDATE public.exercises SET name = 'Pasada alternada con crunch' WHERE name = 'Alternating sit-through with crunch';
UPDATE public.exercises SET name = 'Piedras Atlas' WHERE name = 'Atlas Stones';
UPDATE public.exercises SET name = 'Peso muerto con barra gruesa' WHERE name = 'Axle Deadlift';
UPDATE public.exercises SET name = 'Extensiones lumbares' WHERE name = 'Back extension';
UPDATE public.exercises SET name = 'Tabla de equilibrio' WHERE name = 'Balance Board';
UPDATE public.exercises SET name = 'Aducciones de cadera con banda' WHERE name = 'Band Hip Adductions';
UPDATE public.exercises SET name = 'Sentadilla con barra a cajón' WHERE name = 'Barbell back squat to box';
UPDATE public.exercises SET name = 'Encogimientos con barra por detrás' WHERE name = 'Barbell behind-the-back shrug';
UPDATE public.exercises SET name = 'Press de banca con barra - Agarre medio' WHERE name = 'Barbell Bench Press - Medium Grip';
UPDATE public.exercises SET name = 'Curl con barra' WHERE name = 'Barbell Curl';
UPDATE public.exercises SET name = 'Peso muerto con barra' WHERE name = 'Barbell Deadlift';
UPDATE public.exercises SET name = 'Peso muerto con déficit' WHERE name = 'Barbell deficit deadlift';
UPDATE public.exercises SET name = 'Sentadilla completa con barra' WHERE name = 'Barbell Full Squat';
UPDATE public.exercises SET name = 'Puente de glúteos con barra' WHERE name = 'Barbell glute bridge';
UPDATE public.exercises SET name = 'Hip thrust con barra' WHERE name = 'Barbell Hip Thrust';
UPDATE public.exercises SET name = 'Gemelos sentado con barra' WHERE name = 'Barbell Seated Calf Raise';
UPDATE public.exercises SET name = 'Encogimientos con barra' WHERE name = 'Barbell shrug';
UPDATE public.exercises SET name = 'Remo con barra inclinado a dos manos' WHERE name = 'Bent Over Two-Arm Long Bar Row';
UPDATE public.exercises SET name = 'Curl de bíceps a press de hombros' WHERE name = 'Biceps curl to shoulder press';
UPDATE public.exercises SET name = 'Aperturas con peso corporal' WHERE name = 'Bodyweight Flyes';
UPDATE public.exercises SET name = 'Press invertido con kettlebell' WHERE name = 'Bottoms Up';
UPDATE public.exercises SET name = 'Push-down en polea con barra V' WHERE name = 'Cable V-bar push-down';
UPDATE public.exercises SET name = 'Prensa de gemelos' WHERE name = 'Calf Press';
UPDATE public.exercises SET name = 'Prensa de gemelos en máquina' WHERE name = 'Calf Press On The Leg Press Machine';
UPDATE public.exercises SET name = 'Encogimientos en máquina de gemelos' WHERE name = 'Calf-Machine Shoulder Shrug';
UPDATE public.exercises SET name = 'Fondos en paralelas (pecho)' WHERE name = 'Chest dip';
UPDATE public.exercises SET name = 'Estiramiento mentón al pecho' WHERE name = 'Chin To Chest Stretch';
UPDATE public.exercises SET name = 'Almeja (glúteo medio)' WHERE name = 'Clam';
UPDATE public.exercises SET name = 'Peso muerto de cargada' WHERE name = 'Clean Deadlift';
UPDATE public.exercises SET name = 'Cargada desde bloques' WHERE name = 'Clean from Blocks';
UPDATE public.exercises SET name = 'Press de banca con agarre cerrado' WHERE name = 'Close-grip bench press';
UPDATE public.exercises SET name = 'Jalón al pecho con agarre cerrado' WHERE name = 'Close-Grip Front Lat Pulldown';
UPDATE public.exercises SET name = 'Jalón con agarre cerrado' WHERE name = 'Close-grip pull-down';
UPDATE public.exercises SET name = 'Abdominal cocoon' WHERE name = 'Cocoons';
UPDATE public.exercises SET name = 'Curl de concentración' WHERE name = 'Concentration curl';
UPDATE public.exercises SET name = 'Peso muerto con bandas' WHERE name = 'Deadlift with Bands';
UPDATE public.exercises SET name = 'Peso muerto con cadenas' WHERE name = 'Deadlift with Chains';
UPDATE public.exercises SET name = 'Aperturas con mancuernas en declinado' WHERE name = 'Decline Dumbbell Flyes';
UPDATE public.exercises SET name = 'Rompecráneos con barra Z en declinado' WHERE name = 'Decline EZ-bar skullcrusher';
UPDATE public.exercises SET name = 'Crunch inverso en declinado' WHERE name = 'Decline reverse crunch';
UPDATE public.exercises SET name = 'Press de banca con mancuernas' WHERE name = 'Dumbbell Bench Press';
UPDATE public.exercises SET name = 'Caminata del granjero con mancuernas' WHERE name = 'Dumbbell farmer''s walk';
UPDATE public.exercises SET name = 'Press de suelo con mancuernas' WHERE name = 'Dumbbell floor press';
UPDATE public.exercises SET name = 'Aperturas con mancuernas' WHERE name = 'Dumbbell Flyes';
UPDATE public.exercises SET name = 'Rotaciones de tronco con mancuerna' WHERE name = 'Dumbbell spell caster';
UPDATE public.exercises SET name = 'V-sit con jab cruzado' WHERE name = 'Dumbbell V-Sit Cross Jab';
UPDATE public.exercises SET name = 'Plancha sobre codos' WHERE name = 'Elbow plank';
UPDATE public.exercises SET name = 'Curl con barra Z' WHERE name = 'EZ-Bar Curl';
UPDATE public.exercises SET name = 'Rompecráneos con barra Z' WHERE name = 'EZ-Bar Skullcrusher';
UPDATE public.exercises SET name = 'Curl araña con barra Z' WHERE name = 'EZ-bar spider curl';
UPDATE public.exercises SET name = 'Patada de hidrante' WHERE name = 'Fire Hydrant';
UPDATE public.exercises SET name = 'Curl inclinado con mancuernas' WHERE name = 'Flexor Incline Dumbbell Curls';
UPDATE public.exercises SET name = 'Patadas de tijera' WHERE name = 'Flutter Kicks';
UPDATE public.exercises SET name = 'Puente de glúteos' WHERE name = 'Glute bridge';
UPDATE public.exercises SET name = 'Glute-ham raise (GHR)' WHERE name = 'Glute ham raise-';
UPDATE public.exercises SET name = 'Patada de glúteo' WHERE name = 'Glute Kickback';
UPDATE public.exercises SET name = 'Estiramiento de ingle y espalda' WHERE name = 'Groin and Back Stretch';
UPDATE public.exercises SET name = 'Apertura de cadera (groiner)' WHERE name = 'Groiners';
UPDATE public.exercises SET name = 'Curl martillo' WHERE name = 'Hammer Curls';
UPDATE public.exercises SET name = 'Cargada colgante (hang clean)' WHERE name = 'Hang Clean';
UPDATE public.exercises SET name = 'Círculos de cadera boca abajo' WHERE name = 'Hip Circles (Prone)';
UPDATE public.exercises SET name = 'Hiperextensiones sin banco' WHERE name = 'Hyperextensions With No Hyperextension Bench';
UPDATE public.exercises SET name = 'Auto-masaje de banda iliotibial' WHERE name = 'Iliotibial band SMR';
UPDATE public.exercises SET name = 'Press inclinado con mancuernas' WHERE name = 'Incline dumbbell bench press';
UPDATE public.exercises SET name = 'Remo inclinado con mancuernas' WHERE name = 'Incline dumbbell row';
UPDATE public.exercises SET name = 'Curl martillo inclinado' WHERE name = 'Incline Hammer Curls';
UPDATE public.exercises SET name = 'Isométrico de cuello - Frente y atrás' WHERE name = 'Isometric Neck Exercise - Front And Back';
UPDATE public.exercises SET name = 'Isométrico de cuello - Laterales' WHERE name = 'Isometric Neck Exercise - Sides';
UPDATE public.exercises SET name = 'Estiramiento de banda IT y glúteo' WHERE name = 'IT Band and Glute Stretch';
UPDATE public.exercises SET name = 'Saltar la soga' WHERE name = 'Jumping rope';
UPDATE public.exercises SET name = 'Tirón alto sumo con kettlebell' WHERE name = 'Kettlebell sumo deadlift high pull';
UPDATE public.exercises SET name = 'Thruster con kettlebell' WHERE name = 'Kettlebell thruster';
UPDATE public.exercises SET name = 'Extensión de tríceps en polea arrodillado' WHERE name = 'Kneeling cable triceps extension';
UPDATE public.exercises SET name = 'Sentadilla arrodillada' WHERE name = 'Kneeling Squat';
UPDATE public.exercises SET name = 'Giros landmine' WHERE name = 'Landmine twist';
UPDATE public.exercises SET name = 'Saltos laterales' WHERE name = 'Lateral hop';
UPDATE public.exercises SET name = 'Encogimientos en máquina de palanca' WHERE name = 'Leverage Shrug';
UPDATE public.exercises SET name = 'Cruces en polea baja' WHERE name = 'Low-cable cross-over';
UPDATE public.exercises SET name = 'Estiramiento de ingle tumbado' WHERE name = 'Lying Bent Leg Groin';
UPDATE public.exercises SET name = 'Cuello con disco boca abajo' WHERE name = 'Lying Face Down Plate Neck Resistance';
UPDATE public.exercises SET name = 'Cuello con disco boca arriba' WHERE name = 'Lying Face Up Plate Neck Resistance';
UPDATE public.exercises SET name = 'Caminata monstruo con banda' WHERE name = 'Monster Walk';
UPDATE public.exercises SET name = 'Muscle-up' WHERE name = 'Muscle Up';
UPDATE public.exercises SET name = 'GHR natural' WHERE name = 'Natural Glute Ham Raise';
UPDATE public.exercises SET name = 'Puente de cuello prono' WHERE name = 'Neck Bridge Prone';
UPDATE public.exercises SET name = 'Auto-masaje de cuello' WHERE name = 'Neck-SMR';
UPDATE public.exercises SET name = 'Remo con mancuerna a un brazo' WHERE name = 'One-Arm Dumbbell Row';
UPDATE public.exercises SET name = 'Remo con barra a un brazo' WHERE name = 'One-Arm Long Bar Row';
UPDATE public.exercises SET name = 'Curl de muñeca prono en banco' WHERE name = 'Palms-down wrist curl over bench';
UPDATE public.exercises SET name = 'Curl de muñeca supino en banco' WHERE name = 'Palms-up wrist curl over bench';
UPDATE public.exercises SET name = 'Cargada de potencia desde bloques' WHERE name = 'Power Clean from Blocks';
UPDATE public.exercises SET name = 'Arranque de potencia' WHERE name = 'Power Snatch';
UPDATE public.exercises SET name = 'Arranque de potencia - variante' WHERE name = 'Power snatch-';
UPDATE public.exercises SET name = 'Dominadas' WHERE name = 'Pull-up';
UPDATE public.exercises SET name = 'Dominadas - variante' WHERE name = 'Pullups';
UPDATE public.exercises SET name = 'Push press' WHERE name = 'Push-press';
UPDATE public.exercises SET name = 'Flexiones cerradas de tríceps' WHERE name = 'Push-Ups - Close Triceps Position';
UPDATE public.exercises SET name = 'Flexiones de brazos' WHERE name = 'Pushups';
UPDATE public.exercises SET name = 'Rack pull con bandas' WHERE name = 'Rack Pull with Bands';
UPDATE public.exercises SET name = 'Sentadilla a cajón con bandas inversas' WHERE name = 'Reverse Band Box Squat';
UPDATE public.exercises SET name = 'Push-down con agarre inverso' WHERE name = 'Reverse Grip Triceps Pushdown';
UPDATE public.exercises SET name = 'Remo inclinado con agarre inverso' WHERE name = 'Reverse-grip bent-over row';
UPDATE public.exercises SET name = 'Transporte pesado (carry)' WHERE name = 'Rickshaw Carry';
UPDATE public.exercises SET name = 'Gemelos de pie con balanceo' WHERE name = 'Rocking Standing Calf Raise';
UPDATE public.exercises SET name = 'Dominadas/jalones estilo Rocky' WHERE name = 'Rocky Pull-Ups/Pulldowns';
UPDATE public.exercises SET name = 'Peso muerto rumano con déficit' WHERE name = 'Romanian Deadlift from Deficit';
UPDATE public.exercises SET name = 'Peso muerto rumano con mancuernas' WHERE name = 'Romanian Deadlift With Dumbbells';
UPDATE public.exercises SET name = 'Trepar la soga' WHERE name = 'Rope climb';
UPDATE public.exercises SET name = 'Remoergómetro' WHERE name = 'Rower';
UPDATE public.exercises SET name = 'Remo sentado en polea' WHERE name = 'Seated Cable Rows';
UPDATE public.exercises SET name = 'Gemelos sentado' WHERE name = 'Seated Calf Raise';
UPDATE public.exercises SET name = 'Curl de dedos sentado' WHERE name = 'Seated finger curl';
UPDATE public.exercises SET name = 'Cuello con arnés sentado' WHERE name = 'Seated Head Harness Neck Resistance';
UPDATE public.exercises SET name = 'Curl de muñeca supino a un brazo sentado' WHERE name = 'Seated One-Arm Dumbbell Palms-Up Wrist Curl';
UPDATE public.exercises SET name = 'Curl de muñeca supino en polea baja sentado' WHERE name = 'Seated Two-Arm Palms-Up Low-Pulley Wrist Curl';
UPDATE public.exercises SET name = 'Remo shotgun' WHERE name = 'Shotgun row';
UPDATE public.exercises SET name = 'Elevaciones laterales de pierna' WHERE name = 'Side Leg Raises';
UPDATE public.exercises SET name = 'Estiramiento de ingle de costado' WHERE name = 'Side Lying Groin Stretch';
UPDATE public.exercises SET name = 'Estiramiento lateral de cuello' WHERE name = 'Side Neck Stretch';
UPDATE public.exercises SET name = 'Extensión de tríceps a un brazo en polea' WHERE name = 'Single-arm cable triceps extension';
UPDATE public.exercises SET name = 'Extensión de cadera a una pierna en polea' WHERE name = 'Single-leg cable hip extension';
UPDATE public.exercises SET name = 'Puente de glúteos a una pierna' WHERE name = 'Single-leg glute bridge';
UPDATE public.exercises SET name = 'Estiramiento cruzado a una pierna' WHERE name = 'Single-leg lying cross-over stretch';
UPDATE public.exercises SET name = 'Prensa a una pierna' WHERE name = 'Single-Leg Press';
UPDATE public.exercises SET name = 'Gemelos en multipower' WHERE name = 'Smith Machine Calf Raise';
UPDATE public.exercises SET name = 'Encogimientos en multipower' WHERE name = 'Smith machine shrug';
UPDATE public.exercises SET name = 'Peso muerto de arranque' WHERE name = 'Snatch Deadlift';
UPDATE public.exercises SET name = 'Gateo araña' WHERE name = 'Spider crawl';
UPDATE public.exercises SET name = 'Gemelos de pie con barra' WHERE name = 'Standing barbell calf raise';
UPDATE public.exercises SET name = 'Curl de muñeca de pie por detrás' WHERE name = 'Standing behind-the-back wrist curl';
UPDATE public.exercises SET name = 'Giro en polea de abajo hacia arriba' WHERE name = 'Standing cable low-to-high twist';
UPDATE public.exercises SET name = 'Elevación de gemelos de pie' WHERE name = 'Standing Calf Raises';
UPDATE public.exercises SET name = 'Encogimientos con mancuernas de pie' WHERE name = 'Standing dumbbell shrug';
UPDATE public.exercises SET name = 'Remo al mentón con mancuernas' WHERE name = 'Standing dumbbell upright row';
UPDATE public.exercises SET name = 'Círculos de cadera de pie' WHERE name = 'Standing Hip Circles';
UPDATE public.exercises SET name = 'Step-up con rodilla arriba' WHERE name = 'Step-up with knee raise';
UPDATE public.exercises SET name = 'Enrollado de muñeca con barra' WHERE name = 'Straight-bar wrist roll-up';
UPDATE public.exercises SET name = 'Peso muerto sumo' WHERE name = 'Sumo deadlift';
UPDATE public.exercises SET name = 'Superman (lumbares)' WHERE name = 'Superman';
UPDATE public.exercises SET name = 'Abdominales en suspensión' WHERE name = 'Suspended ab fall-out';
UPDATE public.exercises SET name = 'Remo con barra T' WHERE name = 'T-Bar Row';
UPDATE public.exercises SET name = 'Remo con barra T con agarre' WHERE name = 'T-Bar Row with Handle';
UPDATE public.exercises SET name = 'Abductores en máquina' WHERE name = 'Thigh abductor';
UPDATE public.exercises SET name = 'Aductores en máquina' WHERE name = 'Thigh adductor';
UPDATE public.exercises SET name = 'Volteo de neumático' WHERE name = 'Tire flip';
UPDATE public.exercises SET name = 'Fondos de tríceps' WHERE name = 'Triceps dip';
UPDATE public.exercises SET name = 'Dominadas con barra V' WHERE name = 'V-bar pull-up';
UPDATE public.exercises SET name = 'Fondos lastrados' WHERE name = 'Weighted bench dip';
UPDATE public.exercises SET name = 'Gemelos tipo burro lastrados' WHERE name = 'Weighted donkey calf raise';
UPDATE public.exercises SET name = 'Dominadas lastradas' WHERE name = 'Weighted pull-up';
UPDATE public.exercises SET name = 'Curl con barra agarre abierto' WHERE name = 'Wide-grip barbell curl';
UPDATE public.exercises SET name = 'Molinos' WHERE name = 'Windmills';
UPDATE public.exercises SET name = 'Rodillo de muñeca' WHERE name = 'Wrist Roller';
UPDATE public.exercises SET name = 'Curl Zottman' WHERE name = 'Zottman Curl';

-- VERIFICACIÓN (spot check, debe devolver las 3 filas en español):
-- SELECT name FROM public.exercises
-- WHERE name IN ('Dominadas', 'Peso muerto con barra', 'Sentadilla completa con barra');
